micronaut:
  application:
    name: pix
datasources:
  default:
    url: jdbc:mysql://localhost/pix?createDatabaseIfNotExist = true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: mysql
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true