micronaut:
  application:
    name: pix
datasources:
  default:
    url: jdbc:mysql://localhost/pix?createDatabaseIfNotExist = true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: mysql
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true


sistemaExternos:
  contasItau: ${CONTAS_ITAU:`http://localhost:9091/api/v1/clientes`}
  bbc: ${BBC:`http://localhost:8082/api/v1/pix/keys`}