micronaut:
  application:
    name: pix
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost/pix?createDatabaseIfNotExist = true`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username:  ${DB_USER:`root`}
    password: ${DB_PASSWORD:`root`}
    dialect: mysql
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true


sistemaExternos:
  contasItau: ${CONTAS_ITAU:`http://localhost:9091/api/v1/clientes`}
  bbc: ${BBC:`http://localhost:8082/api/v1/pix/keys`}